typography_spectrum: 0.87078
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.43743906053714454
  lightness: 0.3651461696717888
  saturation: 0.37675629393197596
  rhythmicContrast: 0.5415609215851873
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.51638
analytics:
  google: null
  facebook: null
  twitter: null
name: Fragments of Shadow
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Fragments of Shadow
purpose: []
